# yaml-language-server: $schema=https://blue-build.org
name: zeit-os
description: Zeit-OS is a custom image for Fedora Sway Atomic.

base-image: ghcr.io/wayblueorg/sway
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /
 
  - type: dnf
    repos:
      copr:
        - swayfx/swayfx
        - lihaohong/yazi
        - tofik/nwg-shell
    
    replace:
      - from-repo: copr:copr.fedorainfracloud.org:swayfx:swayfx
        packages:
          - old: sway
            new: swayfx

    install:
      packages:
        - git
        - micro
        - btop     
        - pamixer
        - grimshot
        - slurp
        - swappy
        - fzf
        - yazi
        - nwg-look 
        - nwg-bar
        - godot
        - curl
        - gtklock
        
    remove:
      packages:
        - swaylock
        - firefox
        - firefox-langpacks
  
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - io.gitlab.librewolf-community
        uninstall:
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user

  - type: script
    snippets:
      - |
        curl -L https://zed.dev/api/releases/stable/latest/zed-linux-x86_64.tar.gz -o /tmp/zed.tar.gz
        tar -xzf /tmp/zed.tar.gz -C /tmp/
        
        mkdir -p /var/usrlocal/bin
        mv /tmp/zed-linux-x86_64/bin/zed /var/usrlocal/bin/zed
        mv /tmp/zed-linux-x86_64/libexec/zed-editor /var/usrlocal/bin/zed-editor
        
        mkdir -p /var/usrlocal/share/applications
        mv /tmp/zed-linux-x86_64/share/applications/zed.desktop /var/usrlocal/share/applications/zed.desktop
        sed -i 's|Exec=zed|Exec=/var/usrlocal/bin/zed|g' /var/usrlocal/share/applications/zed.desktop
        
        rm -rf /tmp/zed.tar.gz /tmp/zed-linux-x86_64

  - type: signing
