# yaml-language-server: $schema=https://blue-build.org
name: zeit-os
description: Zeit-OS is a custom image for Fedora Sway Atomic.

base-image: ghcr.io/wayblueorg/sway
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /
 
  - type: dnf
    repos:
      copr:
        - swayfx/swayfx
        - lihaohong/yazi
        - tofik/nwg-shell
      repo-files:
        - https://repo.librewolf.net/librewolf.repo
    replace:
      - from-repo: copr:copr.fedorainfracloud.org:swayfx:swayfx
        packages:
          - old: sway
            new: swayfx

    install:
      packages:
        - git
        - micro
        - btop     
        - pamixer
        - grimshot
        - slurp
        - swappy
        - fzf
        - yazi
        - nwg-look 
        - nwg-bar
        - godot
        - curl
        - gtklock
        - podman
        - podman-compose
        - gimp
        - librewolf

  - type: signing
