# yaml-language-server: $schema=https://blue-build.org
name: zeit-os
description: This is my personal OS image with SwayFX.

base-image: ghcr.io/ublue-os/sway-atomic-main
image-version: '44'

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - swayfx/swayfx
        - lihaohong/yazi
    swap:
      - from: sway
        to: swayfx
    install:
      packages:
        - micro
        - librewolf
        - btop
        - fuzzel
        - pamixer
        - grimshot
        - slurp
        - swappy
        - fzf
        - yazi
        - nwg-look
        - nwg-bar
        - godot
        - curl
    remove:
      packages:
        - rofi
        - firefox
        - firefox-langpacks
  
  - type: script
    snippets:
      - curl -f https://zed.dev/install.sh | HOME=/usr/local/ share_dir=/usr/local/share bin_dir=/usr/local/bin sh

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system     
      - scope: user

  - type: signing
